# Generate the secrets with `rails secret`
# Use Dot Env Gem to load secrets
development:
  secret_key_base: ENV['RAILS_SECRET_KEY_DEV']

test:
  secret_key_base: ENV['RAILS_SECRET_KEY_TEST']

production:
  secret_key_base: ENV['RAILS_SECRET_KEY_PROD']
